version: '3'
services:
  ubicoustics:
     image: ubicoustics:latest
     container_name: ubicoustics
     environment:
       - MICROPHONE_INDEX=0  # change to a mic that's available (check docker logs)
       - CONTEXT=everything  # optional
     devices:
       - "/dev/snd:/dev/snd"
     restart: always
